import type { Server } from 'miragejs';
import affiliateEarningsPayouts from './affiliate-earnings-payouts';
import affiliateLinks from './affiliate-links';
import affiliateReferrals from './affiliate-referrals';
import analyticsEvents from './analytics-events';
import autofixRequests from './autofix-requests';
import badges from './badges';
import charges from './charges';
import codeWalkthroughs from './code-walkthroughs';
import communityCourseStageSolutionComments from './community-course-stage-solution-comments';
import communityCourseStageSolutions from './community-course-stage-solutions';
import communitySolutionEvaluations from './community-solution-evaluations';
import communitySolutionEvaluators from './community-solution-evaluators';
import communitySolutionExports from './community-solution-exports';
import communitySolutionsAnalyses from './community-solutions-analyses';
import conceptEngagements from './concept-engagements';
import conceptGroups from './concept-groups';
import conceptQuestions from './concept-questions';
import concepts from './concepts';
import contests from './contests';
import courseDefinitionUpdates from './course-definition-updates';
import courseExtensionActivations from './course-extension-activations';
import courseExtensionIdeas from './course-extension-ideas';
import courseIdeas from './course-ideas';
import courseLanguageRequests from './course-language-requests';
import courseLeaderboardEntries from './course-leaderboard-entries';
import courseStageComments from './course-stage-comments';
import courseStageCompletions from './course-stage-completions';
import courseStageFeedbackSubmissions from './course-stage-feedback-submissions';
import courseTesterVersions from './course-tester-versions';
import courses from './courses';
import downvotes from './downvotes';
import emailAddresses from './email-addresses';
import fakeSubmissionLogs from './fake-submission-logs';
import featureSuggestions from './feature-suggestions';
import freeUsageGrants from './free-usage-grants';
import giftPaymentFlows from './gift-payment-flows';
import githubAppInstallations from './github-app-installations';
import githubRepositorySyncConfigurations from './github-repository-sync-configurations';
import individualCheckoutSessions from './individual-checkout-sessions';
import individualPaymentMethodUpdateRequests from './individual-payment-method-update-requests';
import institutionMembershipGrantApplications from './institution-membership-grant-applications';
import institutions from './institutions';
import languages from './languages';
import leaderboardEntries from './leaderboard-entries';
import leaderboardRankCalculations from './leaderboard-rank-calculations';
import logstreams from './logstreams';
import membershipGifts from './membership-gifts';
import onboardingSurveys from './onboarding-surveys';
import perks from './perks';
import promotionalDiscounts from './promotional-discounts';
import referralActivations from './referral-activations';
import referralLinks from './referral-links';
import regionalDiscounts from './regional-discounts';
import repositories from './repositories';
import sessions from './sessions';
import siteFeedbackSubmissions from './site-feedback-submissions';
import slackIntegrations from './slack-integrations';
import solutionComparisons from './solution-comparisons';
import submissions from './submissions';
import subscriptions from './subscriptions';
import teamMemberships from './team-memberships';
import teamPaymentFlows from './team-payment-flows';
import teamPaymentMethodUpdateRequests from './team-payment-method-update-requests';
import teamSubscriptions from './team-subscriptions';
import teams from './teams';
import trustedCommunitySolutionEvaluations from './trusted-community-solution-evaluations';
import upvotes from './upvotes';
import users from './users';
import views from './views';

export default function handlers(server: Server) {
  affiliateEarningsPayouts(server);
  affiliateLinks(server);
  affiliateReferrals(server);
  analyticsEvents(server);
  autofixRequests(server);
  badges(server);
  charges(server);
  codeWalkthroughs(server);
  communityCourseStageSolutionComments(server);
  communityCourseStageSolutions(server);
  communitySolutionEvaluations(server);
  communitySolutionEvaluators(server);
  communitySolutionExports(server);
  communitySolutionsAnalyses(server);
  conceptEngagements(server);
  conceptGroups(server);
  conceptQuestions(server);
  concepts(server);
  contests(server);
  courseDefinitionUpdates(server);
  courseExtensionActivations(server);
  courseExtensionIdeas(server);
  courseIdeas(server);
  courseLanguageRequests(server);
  courseLeaderboardEntries(server);
  courseStageComments(server);
  courseStageCompletions(server);
  courseStageFeedbackSubmissions(server);
  courseTesterVersions(server);
  courses(server);
  downvotes(server);
  emailAddresses(server);
  fakeSubmissionLogs(server);
  featureSuggestions(server);
  freeUsageGrants(server);
  giftPaymentFlows(server);
  githubAppInstallations(server);
  githubRepositorySyncConfigurations(server);
  individualCheckoutSessions(server);
  individualPaymentMethodUpdateRequests(server);
  institutionMembershipGrantApplications(server);
  institutions(server);
  languages(server);
  leaderboardEntries(server);
  leaderboardRankCalculations(server);
  logstreams(server);
  membershipGifts(server);
  onboardingSurveys(server);
  perks(server);
  promotionalDiscounts(server);
  referralActivations(server);
  referralLinks(server);
  regionalDiscounts(server);
  repositories(server);
  sessions(server);
  siteFeedbackSubmissions(server);
  slackIntegrations(server);
  solutionComparisons(server);
  submissions(server);
  subscriptions(server);
  teamMemberships(server);
  teamPaymentFlows(server);
  teamPaymentMethodUpdateRequests(server);
  teamSubscriptions(server);
  teams(server);
  trustedCommunitySolutionEvaluations(server);
  upvotes(server);
  users(server);
  views(server);
}
