name: Test Flaky Fix - Claim Offer (Temporary)

on:
  push:
    branches:
      - arpan/cc-1943-fix-flaky-test-in-frontend-repo-re-claim-institution-grant
  workflow_dispatch:

jobs:
  test-flaky-fix:
    runs-on: depot-ubuntu-24.04-16
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - id: cache
        name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-v2-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Run claim offer test 100 times
        run: |
          set -e
          for i in {1..100}; do
            echo "Run $i/100"
            npm run test:ember -- --filter="shows email already in use step if approved application exists"
          done